### ISSUE TITLE
Amount of Players Per Party

### ISSUE THREAD

**Issue by nataliewarden** [darkcloudyskies/ObjectOrientedGameProject#2]
Should we add something that requires each party to start with the same amount of players? I noticed that one party can have multiple players and the other party can have just one. For example: Party1 has two players and Party2 has one player. Once the game starts  Party1 can attack Party2 twice. Once Party2 attacks they can only attack once. This creates an immediate disadvantage for the team with less players.

**Comment by CelestialTechnology** [comment]
This issue has been resolved
